name: bachelor_heaven_landlord
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  get: ^4.6.5
  intl: ^0.17.0
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.3
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  lottie: ^2.2.0
  image_picker: ^0.8.6+4
  fluttertoast: ^8.2.1
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  uuid: ^3.0.7
  http: ^0.13.5
  geocoding: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
